trigger:
- master

extends:
 template: azure-pipelines-buildAndTest-template.yml
 parameters: 
  buildConfiguration: 'Release'

stages:
 - stage: Deployig
    jobs:
     job: DeployToDocker
      dependsOn: Test
      condition: failed()
      steps:
       - task: Docker@2
          displayName: BuildingAndPushing
          inputs:
           command: 'buildAndPush'
           repository: ''
           containerRegistry: 'DockerHub'
           dockerfile: '**/TeamsNotificationService/Dockerfile'
           buildContext: '$(Build.Repository.LocalPath)'
           tags: |
            $(Build.BuildId)
            latest