trigger:
- development

pool:
  name: Default
  demands:
  - msbuild
  - visualstudio
  - vstest

extends:
  template: azure-pipelines-buildAndTest-template.yml
  parameters:
    buildConfiguration: 'Debug'