trigger:
- master

pool:
  name: Azure Pipelines

extends:
 template: azure-pipelines-buildAndTest-template.yml
 parameters: 
  buildConfiguration: 'Release'

stages:
- stage: Deployig
  dependsOn: Test
  jobs:
  - job: DeployToDocker
    steps:
    - task: Docker@2
      displayName: BuildingAndPushing
      inputs:
       command: 'buildAndPush'
       repository: 'ihordeveloper/ihorstudy'
       containerRegistry: 'DockerHub'
       dockerfile: '**/TeamsNotificationService/Dockerfile'
       buildContext: '$(Build.Repository.LocalPath)'
       tags: |
        $(Build.BuildId)
        latest